# Docker compose file

version: "3"

services:
  envoy-logger:
    image: envoy-logger-image:latest
    environment:
      - ENVOY_LOGGER_CFG_PATH=/etc/envoy_logger/cfg.yaml
    volumes:
      - /hd-lowrel0/envoy_logger:/etc/envoy_logger:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
